### ISSUE TITLE
Add handling for German Variations

### ISSUE THREAD

**Issue by kayernyc** [kayernyc/verb-practice-monorepo#19]
All verbs should be arrays of variations, although most verbs will only have one member

Given a structure like:

```yaml
bidden:
  language: de
  variations:
    - definition: as in an auction
      language: de
      translations:
        en: bid
      participle: bid
      irregular:
        past: bid
    - definition: meaning "request"
      translations:
        en: request
      participle: [bade, bid]
      irregular:
        past: bidden, bid
```

the resulting object variation array should have two members.
